# Generated by Django 3.1.5 on 2021-03-07 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='authro',
            new_name='author',
        ),
    ]
