# Generated by Django 3.1.5 on 2021-02-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210208_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='instructor',
            field=models.BooleanField(default=True),
        ),
    ]
